refactor: change to one ci-cd file, now made ci part fully done, testing it now

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,1 +1,229 @@
-# TODO: add here the triggers, and call the files.
+name: CI/CD Pipeline - Build, Test, Push & Deploy
+
+on:
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
+# Variables for this workflow
+env:
+  BE_IMAGE_NAME: rac-backend
+  FE_IMAGE_NAME: rac-frontend
+  DOCKER_REGISTRY: docker.io/poetoecuva
+  APP_NAME: rac-app
+  # Application name and version. Use Git commit id to create unique uploads and link back to commits
+  APP_NAME_VERSION: "rac-app-${{ github.sha }}"
+
+jobs:
+  # Step 1: Test GitHub Repository Environment Variables
+  env-test:
+    runs-on: ubuntu-latest
+    # Use the main environment from GitHub to load environment variables
+    environment: main
+    steps:
+      - name: Test Environment Variables
+        run: |
+          echo "API name: ${{ vars.API_NAME }}"
+          echo "API version: ${{ vars.API_VERSION }}"
+
+  # Step 2: Reusable Job to Build, Test & Push Docker Images
+  build-test-push:
+    runs-on: ubuntu-latest
+    # Use the main environment from GitHub to load environment variables
+    environment: main
+    strategy:
+      matrix:
+        service: [backend, frontend]  # Runs for both services
+    steps:
+    # Checkout repository
+    - uses: actions/checkout@v2
+
+    # Step to set IMAGE_TAG environment variable
+    - name: Set Image Tag
+      # This will set a variable in the $GITHUB_ENV file, which is available within this specific job 
+      run: |
+        IMAGE_TAG="${{ env.DOCKER_REGISTRY }}/rac-${{ matrix.service }}:latest"
+        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
+    # Step to confirm IMAGE_TAG
+    - name: Print BE_IMAGE_TAG
+      run: echo "Using IMAGE_TAG=${IMAGE_TAG}"
+    
+    # Step to login to Docker Hub
+    - name: Login to Docker Container Registry
+      uses: docker/login-action@v1
+      with:
+        # Use repository secrets from GitHub for Docker Hub username
+        username: ${{ secrets.DOCKER_USERNAME }}
+        # Use repository secrets from GitHub for Docker Hub access token: https://docs.docker.com/security/for-developers/access-tokens/
+        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
+    
+    # Step to build Docker container
+    - name: Build Docker Image
+      run: |
+        cd ${{ matrix.service }}
+        docker build --build-arg NAME="rac-${{ matrix.service }}" -t "${IMAGE_TAG}" .
+    
+    # Manually create a .env file in this job with the environment variables for each service
+    # > creates (or overwrites) the file .env, and >> appends to the file (adds content to an existing file)
+    # Names must be exactly the same as the dummy.env files, otherwise the variables cannot be found by the source code
+    - name: Create .env file (backend)
+      if: matrix.service == 'backend'
+      run: |
+        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
+        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
+        echo "FACTOR=${{ secrets.FACTOR }}" >> .env
+        echo "ROLE=${{ secrets.ROLE }}" >> .env
+        echo "API_NAME=${{ vars.API_NAME }}" >> .env
+        echo "API_PORT=${{ vars.API_PORT }}" >> .env
+        echo "API_VERSION=${{ vars.API_VERSION }}" >> .env
+        echo "FRONTEND_URL=${{ vars.FRONTEND_URL }}" >> .env
+        echo "BACKEND_URL=${{ vars.BACKEND_URL }}" >> .env
+        echo "VEHICLE_URL=${{ vars.VEHICLE_URL }}" >> .env
+    # Create a different .env file for the frontend
+    - name: Create .env file (frontend)
+      if: matrix.service == 'frontend'
+      run: |
+        echo "NEXT_PUBLIC_FRONTEND_URL=${{ vars.NEXT_PUBLIC_FRONTEND_URL }}" >> .env
+        echo "NEXT_PUBLIC_BACKEND_FULL_URL=${{ vars.NEXT_PUBLIC_BACKEND_FULL_URL }}" >> .env
+    # Step to run Docker container
+    # Run docker in detached mode (-d) to run the container in the background
+    # Use the .env file just created, since -e caused the docker run command to crash, specifically MONGO_URI for backend
+    # Select the correct port using the service
+    - name: Run Container with Environment Variables
+      run: |
+        if [ "${{ matrix.service }}" == "backend" ]; then
+          PORT=${{ vars.API_PORT }}
+        else
+          PORT=${{ vars.FRONTEND_PORT }}
+        fi
+
+        docker run -d \
+          --env-file .env \
+          -p $PORT:$PORT \
+          --name rac-${{ matrix.service }} \
+          $IMAGE_TAG
+    # Delete the .env file just to be sure (probably also done automatically, but for security reasons manually delete it as well)
+    - name: Delete .env File After Use
+      run: rm -f .env
+    
+    # Step to wait for the container to be ready and running tests
+    # 'until curl -s' silently tries to fetch the backend URL, retrying every 2 seconds 
+    # and timing out after 15 seconds
+    - name: Wait for Container to Start
+      run: |
+        echo "Waiting for container $IMAGE_TAG to be ready..."
+        timeout 15 sh -c 'until curl -s ${{ vars.BACKEND_URL }}; do sleep 2; done'
+        echo "Backend is ready!"
+        
+    # Step to run `npm run test` inside the running container
+    # (environment variables should already be present in the docker container, as they are set in the docker run step)
+    - name: Run Container Tests
+      run: |
+        if [ "${{ matrix.service }}" == "backend" ]; then
+          IMAGE_NAME=${{ env.BE_IMAGE_NAME }}
+        else
+          IMAGE_NAME=${{ env.FE_IMAGE_NAME }}
+        fi
+
+        docker exec $IMAGE_NAME npm run test
+    # If tests fail, stop execution before pushing
+    - name: Fail if tests fail
+      if: failure()
+      run: exit 1
+    
+    # Push image to Docker Hub if builds and tests were successful
+    - name: Push Docker Image to Docker Hub
+      run: docker push "${IMAGE_TAG}"
+
+  # Step 3: Deployment (Only if CI Steps Succeed)
+  deploy-app:
+    name: Deploy Application
+    runs-on: ubuntu-latest
+    needs: build-test-push  # Only run if CI steps pass
+    environment: main
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Login to Docker Hub
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
+
+    - name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ vars.AWS_REGION }}
+
+    - name: Verify AWS Credentials
+      run: aws sts get-caller-identity
+
+    - name: Install or Update AWS CLI
+      run: |
+        echo "Searching for installed aws location..."
+        AWS_PATH=$(which aws)
+        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+        unzip -q awscliv2.zip
+
+        if [ -n "$AWS_PATH" ]; then
+          echo "Updating AWS CLI"
+          INSTALL_DIR=$(ls -l "$AWS_PATH" | awk '{print $NF}' | sed 's|/aws$||')
+          sudo ./aws/install --bin-dir "$AWS_PATH" --install-dir "$INSTALL_DIR" --update
+        else
+          echo "Installing AWS CLI"
+          sudo ./aws/install
+        fi
+
+    - name: Get Deployed AWS EB Environment URL
+      run: |
+        PUBLIC_APP_URL=$(aws elasticbeanstalk describe-environments \
+          --application-name "${{ vars.EB_APP_NAME }}" \
+          --environment-names "${{ vars.EB_ENV_NAME }}" \
+          --query "Environments[0].CNAME" \
+          --output text)
+
+        echo "DEPLOYED_BACKEND_URL=http://$PUBLIC_APP_URL:${{ vars.API_PORT }}" >> $GITHUB_ENV
+        echo "NEXT_PUBLIC_BACKEND_FULL_URL=$DEPLOYED_BACKEND_URL" >> $GITHUB_ENV
+
+    - name: Create .env File for Deployment
+      run: |
+        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
+        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
+        echo "FACTOR=${{ secrets.FACTOR }}" >> .env
+        echo "ROLE=${{ secrets.ROLE }}" >> .env
+        echo "API_NAME=${{ vars.API_NAME }}" >> .env
+        echo "API_PORT=${{ vars.API_PORT }}" >> .env
+        echo "API_VERSION=${{ vars.API_VERSION }}" >> .env
+        echo "FRONTEND_URL=${{ vars.FRONTEND_URL }}" >> .env
+        echo "BACKEND_URL=${{ vars.BACKEND_URL }}" >> .env
+        echo "VEHICLE_URL=${{ vars.VEHICLE_URL }}" >> .env
+        echo "S3_BUCKET_NAME=${{ vars.S3_BUCKET_NAME }}" >> .env
+        echo "NEXT_PUBLIC_FRONTEND_URL=http://$PUBLIC_APP_URL" >> .env
+
+    - name: Move `.platform` Folder to Root
+      run: mv infrastructure/extensions/.platform .platform
+
+    - name: Package Application for AWS EB
+      run: zip -r "${{ env.APP_NAME }}.zip" .env docker-compose.yml .platform/
+
+    - name: Delete .env File for Security
+      run: rm -f .env
+
+    - name: Upload Application to S3
+      run: aws s3 cp "${{ env.APP_NAME }}.zip" "s3://${{ vars.S3_BUCKET_NAME }}/${{ env.APP_NAME_VERSION }}.zip"
+
+    - name: Deploy Application to AWS EB
+      run: |
+        aws elasticbeanstalk create-application-version --application-name "${{ vars.EB_APP_NAME }}" \
+          --version-label "${{ env.APP_NAME_VERSION }}" \
+          --source-bundle S3Bucket="${{ vars.S3_BUCKET_NAME }}",S3Key="${{ env.APP_NAME_VERSION }}.zip"
+
+        aws elasticbeanstalk update-environment --environment-name ${{ vars.EB_ENV_NAME }} \
+          --version-label "${{ env.APP_NAME_VERSION }}"
